// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :one
INSERT INTO conversation_members (conversation_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id) DO NOTHING
RETURNING id
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.Role)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, name, admin_id)
VALUES ($1, $2, $3)
RETURNING id, type, name, admin_id, created_at, updated_at
`

type CreateConversationParams struct {
	Type    string      `json:"type"`
	Name    string      `json:"name"`
	AdminID pgtype.UUID `json:"admin_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.Name, arg.AdminID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const findPrivateConversation = `-- name: FindPrivateConversation :one
SELECT c.id, c.type, c.name, c.admin_id, c.created_at, c.updated_at
FROM conversations c
WHERE c.type = 'private'
  AND EXISTS (
    SELECT 1 FROM conversation_members cm1
    WHERE cm1.conversation_id = c.id AND cm1.user_id = $1
  )
  AND EXISTS (
    SELECT 1 FROM conversation_members cm2
    WHERE cm2.conversation_id = c.id AND cm2.user_id = $2
  )
LIMIT 1
`

type FindPrivateConversationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) FindPrivateConversation(ctx context.Context, arg FindPrivateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findPrivateConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT c.id, c.type, c.name, c.admin_id, c.created_at, c.updated_at,
       COALESCE(
         (SELECT json_agg(json_build_object(
           'user_id', cm.user_id,
           'username', u.username,
           'role', cm.role,
           'joined_at', cm.joined_at
         )) FROM conversation_members cm JOIN users u ON cm.user_id = u.id WHERE cm.conversation_id = c.id),
         '[]'::json
       ) AS members
FROM conversations c
WHERE c.id = $1
`

type GetConversationByIDRow struct {
	ID        uuid.UUID   `json:"id"`
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	AdminID   pgtype.UUID `json:"admin_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Members   interface{} `json:"members"`
}

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (GetConversationByIDRow, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i GetConversationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Members,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT cm.user_id, u.username, cm.role, cm.joined_at
FROM conversation_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.conversation_id = $1
`

type GetConversationMembersRow struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]GetConversationMembersRow, error) {
	rows, err := q.db.Query(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationMembersRow{}
	for rows.Next() {
		var i GetConversationMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(
  SELECT 1 FROM conversation_members
  WHERE conversation_id = $1 AND user_id = $2
) AS is_member
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.type, c.name, c.admin_id, c.created_at, c.updated_at,
       COALESCE(
         (SELECT json_agg(json_build_object(
           'user_id', cm.user_id,
           'username', u.username,
           'role', cm.role,
           'joined_at', cm.joined_at
         )) FROM conversation_members cm JOIN users u ON cm.user_id = u.id WHERE cm.conversation_id = c.id),
         '[]'::json
       ) AS members,
       (SELECT m.content FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1) AS last_message_content,
       (SELECT m.created_at FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1) AS last_message_at
FROM conversations c
JOIN conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY COALESCE(
  (SELECT m.created_at FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1),
  c.created_at
) DESC
`

type ListUserConversationsRow struct {
	ID                 uuid.UUID   `json:"id"`
	Type               string      `json:"type"`
	Name               string      `json:"name"`
	AdminID            pgtype.UUID `json:"admin_id"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	Members            interface{} `json:"members"`
	LastMessageContent *string     `json:"last_message_content"`
	LastMessageAt      *time.Time  `json:"last_message_at"`
}

func (q *Queries) ListUserConversations(ctx context.Context, userID uuid.UUID) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Members,
			&i.LastMessageContent,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.Exec(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}
