// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, emoji) DO NOTHING
RETURNING id
`

type AddReactionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, content, type)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, content, type, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Content        string    `json:"content"`
	Type           string    `json:"type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.Type,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1 AND sender_id = $2
`

type DeleteMessageParams struct {
	ID       uuid.UUID `json:"id"`
	SenderID uuid.UUID `json:"sender_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.SenderID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT m.id, m.conversation_id, m.sender_id, u.username AS sender_username, m.content, m.type, m.created_at
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	SenderUsername string    `json:"sender_username"`
	Content        string    `json:"content"`
	Type           string    `json:"type"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.SenderUsername,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT m.id, m.conversation_id, m.sender_id, u.username AS sender_username, m.content, m.type, m.created_at,
       COALESCE(
         (SELECT json_agg(json_build_object(
           'user_id', r.user_id,
           'username', ru.username,
           'emoji', r.emoji,
           'created_at', r.created_at
         )) FROM reactions r JOIN users ru ON r.user_id = ru.id WHERE r.message_id = m.id),
         '[]'::json
       ) AS reactions
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.conversation_id = $1
  AND ($2::uuid IS NULL OR m.id < $2::uuid)
ORDER BY m.created_at DESC
LIMIT $3
`

type ListMessagesByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Column2        uuid.UUID `json:"column_2"`
	Limit          int32     `json:"limit"`
}

type ListMessagesByConversationRow struct {
	ID             uuid.UUID   `json:"id"`
	ConversationID uuid.UUID   `json:"conversation_id"`
	SenderID       uuid.UUID   `json:"sender_id"`
	SenderUsername string      `json:"sender_username"`
	Content        string      `json:"content"`
	Type           string      `json:"type"`
	CreatedAt      time.Time   `json:"created_at"`
	Reactions      interface{} `json:"reactions"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]ListMessagesByConversationRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, arg.ConversationID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByConversationRow{}
	for rows.Next() {
		var i ListMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.Content,
			&i.Type,
			&i.CreatedAt,
			&i.Reactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM reactions WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}
