// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (uuid.UUID, error)
	AddReaction(ctx context.Context, arg AddReactionParams) (uuid.UUID, error)
	CleanExpiredSessions(ctx context.Context) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	FindPrivateConversation(ctx context.Context, arg FindPrivateConversationParams) (Conversation, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (GetConversationByIDRow, error)
	GetConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]GetConversationMembersRow, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (GetMessageByIDRow, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (GetSessionByTokenRow, error)
	GetUnreadNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error)
	ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]ListMessagesByConversationRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListUserConversations(ctx context.Context, userID uuid.UUID) ([]ListUserConversationsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
